name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: deno ${{ matrix.deno-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno-version: [v1.x, vx.x.x]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Cache
        run: deno task cache

      - name: Test
        run: deno task test:cover

      - name: Print coverage
        run: deno task coverage
